### ISSUE TITLE
Error in create Font

### ISSUE THREAD

**Issue by thigiacmay** [Tape-Worm/Gorgon#13]
I use this function to init **two fonts for two text sprites**

```
GorgonFontFactory _fontFactory ;
GorgonFont _SubjectNameFont;
GorgonFont _SubjectIDFont;
GorgonTextSprite _SubjectName { get; set; }
GorgonTextSprite _SubjectID { get; set; }
public void InitFont()
        {
            int[] font= new int[]{0x0000, 0x0001, 0x1EB2, 0x0003, 0x0004, 0x1EB4, 0x1EAA, 0x0007,
                                    0x0008, 0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x000e, 0x000f,
                                    0x0010, 0x0011, 0x0012, 0x0013, 0x1EF6, 0x0015, 0x0016, 0x0017,
                                    0x0018, 0x1EF8, 0x001a, 0x001b, 0x001c, 0x001d, 0x1EF4, 0x001f,
                                    0x0020, 0x0021, 0x0022, 0x0023, 0x0024, 0x0025, 0x0026, 0x0027,
                                    0x0028, 0x0029, 0x002A, 0x002B, 0x002C, 0x002D, 0x002E, 0x002F,
                                    0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037,
                                    0x0038, 0x0039, 0x003A, 0x003B, 0x003C, 0x003D, 0x003E, 0x003F,
                                    0x0040, 0x0041, 0x0042, 0x0043, 0x0044, 0x0045, 0x0046, 0x0047,
                                    0x0048, 0x0049, 0x004A, 0x004B, 0x004C, 0x004D, 0x004E, 0x004F,
                                    0x0050, 0x0051, 0x0052, 0x0053, 0x0054, 0x0055, 0x0056, 0x0057,
                                    0x0058, 0x0059, 0x005A, 0x005B, 0x005C, 0x005D, 0x005E, 0x005F,
                                    0x0060, 0x0061, 0x0062, 0x0063, 0x0064, 0x0065, 0x0066, 0x0067,
                                    0x0068, 0x0069, 0x006A, 0x006B, 0x006C, 0x006D, 0x006E, 0x006F,
                                    0x0070, 0x0071, 0x0072, 0x0073, 0x0074, 0x0075, 0x0076, 0x0077,
                                    0x0078, 0x0079, 0x007A, 0x007B, 0x007C, 0x007D, 0x007E, 0x007f,
                                    0x1EA0, 0x1EAE, 0x1EB0, 0x1EB6, 0x1EA4, 0x1EA6, 0x1EA8, 0x1EAC,
                                    0x1EBC, 0x1EB8, 0x1EBE, 0x1EC0, 0x1EC2, 0x1EC4, 0x1EC6, 0x1ED0,
                                    0x1ED2, 0x1ED4, 0x1ED6, 0x1ED8, 0x1EE2, 0x1EDA, 0x1EDC, 0x1EDE,
                                    0x1ECA, 0x1ECE, 0x1ECC, 0x1EC8, 0x1EE6, 0x0168, 0x1EE4, 0x1EF2,
                                    0x00D5, 0x1EAF, 0x1EB1, 0x1EB7, 0x1EA5, 0x1EA7, 0x1EA8, 0x1EAD,
                                    0x1EBD, 0x1EB9, 0x1EBF, 0x1EC1, 0x1EC3, 0x1EC5, 0x1EC7, 0x1ED1,
                                    0x1ED3, 0x1ED5, 0x1ED7, 0x1EE0, 0x01A0, 0x1ED9, 0x1EDD, 0x1EDF,
                                    0x1ECB, 0x1EF0, 0x1EE8, 0x1EEA, 0x1EEC, 0x01A1, 0x1EDB, 0x01AF,
                                    0x00C0, 0x00C1, 0x00C2, 0x00C3, 0x1EA2, 0x0102, 0x1EB3, 0x1EB5,
                                    0x00C8, 0x00C9, 0x00CA, 0x1EBA, 0x00CC, 0x00CD, 0x0128, 0x1EF3,
                                    0x0110, 0x1EE9, 0x00D2, 0x00D3, 0x00D4, 0x1EA1, 0x1EF7, 0x1EEB,
                                    0x1EED, 0x00D9, 0x00DA, 0x1EF9, 0x1EF5, 0x00DD, 0x1EE1, 0x01B0,
                                    0x00E0, 0x00E1, 0x00E2, 0x00E3, 0x1EA3, 0x0103, 0x1EEF, 0x1EAB,
                                    0x00E8, 0x00E9, 0x00EA, 0x1EBB, 0x00EC, 0x00ED, 0x0129, 0x1EC9,
                                    0x0111, 0x1EF1, 0x00F2, 0x00F3, 0x00F4, 0x00F5, 0x1ECF, 0x1ECD,
                                    0x1EE5, 0x00F9, 0x00FA, 0x0169, 0x1EE7, 0x00FD, 0x1EE3, 0x1EEE
                                };

            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < font.Length; i++)
            {
                char character = Convert.ToChar(font[i]);
                sb.Append(character);
            }
            _fontFactory = new GorgonFontFactory(Graphics);

            _SubjectIDFont = _fontFactory.GetFont(new GorgonFontInfo("Segoe UI", 30f, FontHeightMode.Points, "Segoe UI 10pt")
            {
                OutlineSize = 1,
                Characters = sb.ToString(),
                FontStyle = Gorgon.Graphics.Fonts.FontStyle.Bold,
                AntiAliasingMode = FontAntiAliasMode.AntiAlias,
                OutlineColor1 = GorgonColor.Black,
                OutlineColor2 = GorgonColor.Black
            });
            _SubjectNameFont = _fontFactory.GetFont(new GorgoncFontInfo("Segoe UI", 36.0f, FontHeightMode.Points, "Segoe UI 10pt")
            {
                OutlineSize = 1,
                Characters = sb.ToString(),
                
                FontStyle = Gorgon.Graphics.Fonts.FontStyle.Bold,
                AntiAliasingMode = FontAntiAliasMode.AntiAlias,
                OutlineColor1 = GorgonColor.DarkRed,
                OutlineColor2 = GorgonColor.DarkRed
            });
            _SubjectID = new GorgonTextSprite(_SubjectIDFont)
            {
                Position = new Vector2(0, 0),
                DrawMode = TextDrawMode.OutlinedGlyphs,
                Color = new GorgonColor(System.Drawing.Color.Lime),
                Anchor = new Vector2(0.5f, 0.5f),
                Scale = new Vector2(0.8f)
            };
            _SubjectID.Position = new Vector2(Card_Size_Main.Width / 2.0f - _SubjectID.Size.Width / 2, Card_Size_Main.Height - 80);
            _SubjectID.Text = "ID999999999";

            _SubjectName = new GorgonTextSprite(_SubjectNameFont)
            {
                Position = new Vector2(0, 0),
                DrawMode = TextDrawMode.OutlinedGlyphs,
                Color = GorgonColor.Orange,
                Anchor = new Vector2(0.5f, 0.5f)
            };
            _SubjectName.Position = new Vector2(Card_Size_Main.Width / 2.0f - _SubjectName.Size.Width / 2, Card_Size_Main.Height - _SubjectName.Size.Height - 80 - _SubjectID.Size.Height);
            _SubjectName.Text = "WHO ARE YOU?";
        }
```
**I got this error**:
   ```
There was an error during the enumeration process.
   The character code 0x  used by the default character is not valid.

   at Gorgon.Graphics.Fonts.GorgonFont.GetLineWidth(String line, Boolean useOutline)
   at Gorgon.Graphics.Fonts.GorgonFont.MeasureText(String text, Boolean useOutline, Int32 tabSpaceCount, Single lineSpacing, Nullable`1 wordWrapWidth)
   at Gorgonc.Renderers.GorgonTextSprite.UpdateBounds()
   at Gorgon.Renderers.GorgonTextSprite.FormatText()
   at Gorgon.Renderers.GorgonTextSprite.set_Text(String value)
   at JustTest.Subjects.InitFont() in C:\Users\GALAXY\Desktop\JustTest\Subjects.cs:line 256
   at JustTest.Subjects..ctor(GorgonGraphics graphics, Gorgon2D renderer, GorgonSwapChain scene, Size camImageSize) in C:\Users\GALAXY\Desktop\JustTest\Subjects.cs:line 169
   at JustTest.Program.Initialize() in C:\Users\GALAXY\Desktop\JustTest\Program.cs:line 427
   at JustTest.Program.Main(String[] args) in C:\Users\GALAXY\Desktop\JustTest\Program.cs:line 687
```

But if i use only one font for both two text sprites then OK

**Comment by Tape-Worm** [comment]
The issue is that both of your fonts have the same name.  The font factory replaces the font when it has the same name because factory tracks the fonts by name.  This makes your first font invalid. 
Change the name (last parameter of GorgonFontInfo) of your 2nd font and you'll be fine.

I will add a small bug fix to ensure that 2 different fonts with the same name can't be used when the font info is different to avoid issues like this in the future.

**Comment by thigiacmay** [comment]
Thanks, i fixed the error

**Comment by Tape-Worm** [comment]
I've released a new version containing the bug fix I described earlier.  If you create multiple fonts with the same name but with different GorgonFontInfo parameters, it should give you an error describing what went wrong.
